import type { Metadata } from "next";
import { Geist, Geist_Mono, Encode_Sans_SC } from "next/font/google";
import "./globals.css";
import MainHeader from "components/header/mainHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sansSC = Encode_Sans_SC({
  weight: "900",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shift Track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainHeader />

        <main>{children}</main>
      </body>
    </html>
  );
}
